### ISSUE TITLE
Building maven

### ISSUE THREAD

**Issue by silviodc** [sharispe/slib#51]
Hi,
I was testing our framework with the .jar file available on the website, however it seems to be an old version. Therefore, i tried to built a new file using maven, but i got a missing package:

[INFO] ------------------------------------------------------------------------
[INFO] Building slib-sml
[INFO]    task-segment: [package]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 13 resources
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.
## Missing:

1) com.github.sharispe:slib-graph:pom:0.10-SNAPSHOT
  Path to dependency: 
    1) com.github.sharispe:slib-sml:jar:0.10-SNAPSHOT
    2) com.github.sharispe:slib-graph:pom:0.10-SNAPSHOT

---

1 required artifact is missing.

for artifact: 
  com.github.sharispe:slib-sml:jar:0.10-SNAPSHOT

from the specified remote repositories:
  central (https://repo1.maven.org/maven2)

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13 seconds
[INFO] Finished at: Fri Oct 07 11:37:37 CEST 2016

Could you please fix it? Thanks so much!
PS: Congrats for the good work :D

**Comment by sharispe** [comment]
Hi Silvio,

I recommend you to build slib-sml using slib from the dev branch
<https://github.com/sharispe/slib/tree/dev> if you want the latest version.
You should not have problem to build it.
Keep me updated please.

Sincerely,

Sébastien
